/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedLandMappingRouteImport } from './routes/_authenticated/land-mapping'
import { Route as AuthenticatedLand3dRouteImport } from './routes/_authenticated/land-3d'
import { Route as AuthenticatedFrontdeskRouteImport } from './routes/_authenticated/frontdesk'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPayrollIndexRouteImport } from './routes/_authenticated/payroll.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedLandsIndexRouteImport } from './routes/_authenticated/lands.index'
import { Route as AuthenticatedLandownersIndexRouteImport } from './routes/_authenticated/landowners.index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills.index'
import { Route as AuthenticatedSettingsZonesRouteImport } from './routes/_authenticated/settings.zones'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings.system'
import { Route as AuthenticatedSettingsSmsRouteImport } from './routes/_authenticated/settings.sms'
import { Route as AuthenticatedSettingsRentPackagesRouteImport } from './routes/_authenticated/settings.rent-packages'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsLandTypesRouteImport } from './routes/_authenticated/settings.land-types'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings.email'
import { Route as AuthenticatedPayrollStaffRouteImport } from './routes/_authenticated/payroll.staff'
import { Route as AuthenticatedPayrollComponentsRouteImport } from './routes/_authenticated/payroll.components'
import { Route as AuthenticatedLandsLandIdRouteImport } from './routes/_authenticated/lands.$landId'
import { Route as AuthenticatedLandownersOwnerIdRouteImport } from './routes/_authenticated/landowners.$ownerId'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills.$billId'
import { Route as AuthenticatedPayrollRunsRunIdRouteImport } from './routes/_authenticated/payroll.runs.$runId'
import { Route as AuthenticatedPayrollPayslipsPayslipIdRouteImport } from './routes/_authenticated/payroll.payslips.$payslipId'
import { Route as AuthenticatedPaymentsPaymentIdReceiptRouteImport } from './routes/_authenticated/payments.$paymentId.receipt'
import { Route as ApiPublicLandsLandIdKmlRouteImport } from './routes/api/public/lands.$landId.kml'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandMappingRoute =
  AuthenticatedLandMappingRouteImport.update({
    id: '/land-mapping',
    path: '/land-mapping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLand3dRoute = AuthenticatedLand3dRouteImport.update({
  id: '/land-3d',
  path: '/land-3d',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFrontdeskRoute = AuthenticatedFrontdeskRouteImport.update({
  id: '/frontdesk',
  path: '/frontdesk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollIndexRoute =
  AuthenticatedPayrollIndexRouteImport.update({
    id: '/payroll/',
    path: '/payroll/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLandsIndexRoute = AuthenticatedLandsIndexRouteImport.update({
  id: '/lands/',
  path: '/lands/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandownersIndexRoute =
  AuthenticatedLandownersIndexRouteImport.update({
    id: '/landowners/',
    path: '/landowners/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsZonesRoute =
  AuthenticatedSettingsZonesRouteImport.update({
    id: '/settings/zones',
    path: '/settings/zones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSmsRoute =
  AuthenticatedSettingsSmsRouteImport.update({
    id: '/settings/sms',
    path: '/settings/sms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRentPackagesRoute =
  AuthenticatedSettingsRentPackagesRouteImport.update({
    id: '/settings/rent-packages',
    path: '/settings/rent-packages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLandTypesRoute =
  AuthenticatedSettingsLandTypesRouteImport.update({
    id: '/settings/land-types',
    path: '/settings/land-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/settings/email',
    path: '/settings/email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollStaffRoute =
  AuthenticatedPayrollStaffRouteImport.update({
    id: '/payroll/staff',
    path: '/payroll/staff',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollComponentsRoute =
  AuthenticatedPayrollComponentsRouteImport.update({
    id: '/payroll/components',
    path: '/payroll/components',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLandsLandIdRoute =
  AuthenticatedLandsLandIdRouteImport.update({
    id: '/lands/$landId',
    path: '/lands/$landId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLandownersOwnerIdRoute =
  AuthenticatedLandownersOwnerIdRouteImport.update({
    id: '/landowners/$ownerId',
    path: '/landowners/$ownerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollRunsRunIdRoute =
  AuthenticatedPayrollRunsRunIdRouteImport.update({
    id: '/payroll/runs/$runId',
    path: '/payroll/runs/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollPayslipsPayslipIdRoute =
  AuthenticatedPayrollPayslipsPayslipIdRouteImport.update({
    id: '/payroll/payslips/$payslipId',
    path: '/payroll/payslips/$payslipId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsPaymentIdReceiptRoute =
  AuthenticatedPaymentsPaymentIdReceiptRouteImport.update({
    id: '/payments/$paymentId/receipt',
    path: '/payments/$paymentId/receipt',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicLandsLandIdKmlRoute = ApiPublicLandsLandIdKmlRouteImport.update({
  id: '/api/public/lands/$landId/kml',
  path: '/api/public/lands/$landId/kml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frontdesk': typeof AuthenticatedFrontdeskRoute
  '/land-3d': typeof AuthenticatedLand3dRoute
  '/land-mapping': typeof AuthenticatedLandMappingRoute
  '/map': typeof AuthenticatedMapRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/landowners/$ownerId': typeof AuthenticatedLandownersOwnerIdRoute
  '/lands/$landId': typeof AuthenticatedLandsLandIdRoute
  '/payroll/components': typeof AuthenticatedPayrollComponentsRoute
  '/payroll/staff': typeof AuthenticatedPayrollStaffRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/land-types': typeof AuthenticatedSettingsLandTypesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/rent-packages': typeof AuthenticatedSettingsRentPackagesRoute
  '/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/zones': typeof AuthenticatedSettingsZonesRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/landowners/': typeof AuthenticatedLandownersIndexRoute
  '/lands/': typeof AuthenticatedLandsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/payroll/': typeof AuthenticatedPayrollIndexRoute
  '/payments/$paymentId/receipt': typeof AuthenticatedPaymentsPaymentIdReceiptRoute
  '/payroll/payslips/$payslipId': typeof AuthenticatedPayrollPayslipsPayslipIdRoute
  '/payroll/runs/$runId': typeof AuthenticatedPayrollRunsRunIdRoute
  '/api/public/lands/$landId/kml': typeof ApiPublicLandsLandIdKmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frontdesk': typeof AuthenticatedFrontdeskRoute
  '/land-3d': typeof AuthenticatedLand3dRoute
  '/land-mapping': typeof AuthenticatedLandMappingRoute
  '/map': typeof AuthenticatedMapRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/landowners/$ownerId': typeof AuthenticatedLandownersOwnerIdRoute
  '/lands/$landId': typeof AuthenticatedLandsLandIdRoute
  '/payroll/components': typeof AuthenticatedPayrollComponentsRoute
  '/payroll/staff': typeof AuthenticatedPayrollStaffRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/land-types': typeof AuthenticatedSettingsLandTypesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/rent-packages': typeof AuthenticatedSettingsRentPackagesRoute
  '/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/zones': typeof AuthenticatedSettingsZonesRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/landowners': typeof AuthenticatedLandownersIndexRoute
  '/lands': typeof AuthenticatedLandsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/payroll': typeof AuthenticatedPayrollIndexRoute
  '/payments/$paymentId/receipt': typeof AuthenticatedPaymentsPaymentIdReceiptRoute
  '/payroll/payslips/$payslipId': typeof AuthenticatedPayrollPayslipsPayslipIdRoute
  '/payroll/runs/$runId': typeof AuthenticatedPayrollRunsRunIdRoute
  '/api/public/lands/$landId/kml': typeof ApiPublicLandsLandIdKmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/frontdesk': typeof AuthenticatedFrontdeskRoute
  '/_authenticated/land-3d': typeof AuthenticatedLand3dRoute
  '/_authenticated/land-mapping': typeof AuthenticatedLandMappingRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/landowners/$ownerId': typeof AuthenticatedLandownersOwnerIdRoute
  '/_authenticated/lands/$landId': typeof AuthenticatedLandsLandIdRoute
  '/_authenticated/payroll/components': typeof AuthenticatedPayrollComponentsRoute
  '/_authenticated/payroll/staff': typeof AuthenticatedPayrollStaffRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/_authenticated/settings/land-types': typeof AuthenticatedSettingsLandTypesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/rent-packages': typeof AuthenticatedSettingsRentPackagesRoute
  '/_authenticated/settings/sms': typeof AuthenticatedSettingsSmsRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/zones': typeof AuthenticatedSettingsZonesRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/landowners/': typeof AuthenticatedLandownersIndexRoute
  '/_authenticated/lands/': typeof AuthenticatedLandsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/payroll/': typeof AuthenticatedPayrollIndexRoute
  '/_authenticated/payments/$paymentId/receipt': typeof AuthenticatedPaymentsPaymentIdReceiptRoute
  '/_authenticated/payroll/payslips/$payslipId': typeof AuthenticatedPayrollPayslipsPayslipIdRoute
  '/_authenticated/payroll/runs/$runId': typeof AuthenticatedPayrollRunsRunIdRoute
  '/api/public/lands/$landId/kml': typeof ApiPublicLandsLandIdKmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/frontdesk'
    | '/land-3d'
    | '/land-mapping'
    | '/map'
    | '/reports'
    | '/bills/$billId'
    | '/landowners/$ownerId'
    | '/lands/$landId'
    | '/payroll/components'
    | '/payroll/staff'
    | '/settings/email'
    | '/settings/land-types'
    | '/settings/profile'
    | '/settings/rent-packages'
    | '/settings/sms'
    | '/settings/system'
    | '/settings/users'
    | '/settings/zones'
    | '/bills/'
    | '/landowners/'
    | '/lands/'
    | '/payments/'
    | '/payroll/'
    | '/payments/$paymentId/receipt'
    | '/payroll/payslips/$payslipId'
    | '/payroll/runs/$runId'
    | '/api/public/lands/$landId/kml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/frontdesk'
    | '/land-3d'
    | '/land-mapping'
    | '/map'
    | '/reports'
    | '/bills/$billId'
    | '/landowners/$ownerId'
    | '/lands/$landId'
    | '/payroll/components'
    | '/payroll/staff'
    | '/settings/email'
    | '/settings/land-types'
    | '/settings/profile'
    | '/settings/rent-packages'
    | '/settings/sms'
    | '/settings/system'
    | '/settings/users'
    | '/settings/zones'
    | '/bills'
    | '/landowners'
    | '/lands'
    | '/payments'
    | '/payroll'
    | '/payments/$paymentId/receipt'
    | '/payroll/payslips/$payslipId'
    | '/payroll/runs/$runId'
    | '/api/public/lands/$landId/kml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/frontdesk'
    | '/_authenticated/land-3d'
    | '/_authenticated/land-mapping'
    | '/_authenticated/map'
    | '/_authenticated/reports'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/landowners/$ownerId'
    | '/_authenticated/lands/$landId'
    | '/_authenticated/payroll/components'
    | '/_authenticated/payroll/staff'
    | '/_authenticated/settings/email'
    | '/_authenticated/settings/land-types'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/rent-packages'
    | '/_authenticated/settings/sms'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/zones'
    | '/_authenticated/bills/'
    | '/_authenticated/landowners/'
    | '/_authenticated/lands/'
    | '/_authenticated/payments/'
    | '/_authenticated/payroll/'
    | '/_authenticated/payments/$paymentId/receipt'
    | '/_authenticated/payroll/payslips/$payslipId'
    | '/_authenticated/payroll/runs/$runId'
    | '/api/public/lands/$landId/kml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicLandsLandIdKmlRoute: typeof ApiPublicLandsLandIdKmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/land-mapping': {
      id: '/_authenticated/land-mapping'
      path: '/land-mapping'
      fullPath: '/land-mapping'
      preLoaderRoute: typeof AuthenticatedLandMappingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/land-3d': {
      id: '/_authenticated/land-3d'
      path: '/land-3d'
      fullPath: '/land-3d'
      preLoaderRoute: typeof AuthenticatedLand3dRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frontdesk': {
      id: '/_authenticated/frontdesk'
      path: '/frontdesk'
      fullPath: '/frontdesk'
      preLoaderRoute: typeof AuthenticatedFrontdeskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/': {
      id: '/_authenticated/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AuthenticatedPayrollIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lands/': {
      id: '/_authenticated/lands/'
      path: '/lands'
      fullPath: '/lands/'
      preLoaderRoute: typeof AuthenticatedLandsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landowners/': {
      id: '/_authenticated/landowners/'
      path: '/landowners'
      fullPath: '/landowners/'
      preLoaderRoute: typeof AuthenticatedLandownersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/zones': {
      id: '/_authenticated/settings/zones'
      path: '/settings/zones'
      fullPath: '/settings/zones'
      preLoaderRoute: typeof AuthenticatedSettingsZonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/sms': {
      id: '/_authenticated/settings/sms'
      path: '/settings/sms'
      fullPath: '/settings/sms'
      preLoaderRoute: typeof AuthenticatedSettingsSmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/rent-packages': {
      id: '/_authenticated/settings/rent-packages'
      path: '/settings/rent-packages'
      fullPath: '/settings/rent-packages'
      preLoaderRoute: typeof AuthenticatedSettingsRentPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/land-types': {
      id: '/_authenticated/settings/land-types'
      path: '/settings/land-types'
      fullPath: '/settings/land-types'
      preLoaderRoute: typeof AuthenticatedSettingsLandTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/staff': {
      id: '/_authenticated/payroll/staff'
      path: '/payroll/staff'
      fullPath: '/payroll/staff'
      preLoaderRoute: typeof AuthenticatedPayrollStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/components': {
      id: '/_authenticated/payroll/components'
      path: '/payroll/components'
      fullPath: '/payroll/components'
      preLoaderRoute: typeof AuthenticatedPayrollComponentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lands/$landId': {
      id: '/_authenticated/lands/$landId'
      path: '/lands/$landId'
      fullPath: '/lands/$landId'
      preLoaderRoute: typeof AuthenticatedLandsLandIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landowners/$ownerId': {
      id: '/_authenticated/landowners/$ownerId'
      path: '/landowners/$ownerId'
      fullPath: '/landowners/$ownerId'
      preLoaderRoute: typeof AuthenticatedLandownersOwnerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/runs/$runId': {
      id: '/_authenticated/payroll/runs/$runId'
      path: '/payroll/runs/$runId'
      fullPath: '/payroll/runs/$runId'
      preLoaderRoute: typeof AuthenticatedPayrollRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll/payslips/$payslipId': {
      id: '/_authenticated/payroll/payslips/$payslipId'
      path: '/payroll/payslips/$payslipId'
      fullPath: '/payroll/payslips/$payslipId'
      preLoaderRoute: typeof AuthenticatedPayrollPayslipsPayslipIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/$paymentId/receipt': {
      id: '/_authenticated/payments/$paymentId/receipt'
      path: '/payments/$paymentId/receipt'
      fullPath: '/payments/$paymentId/receipt'
      preLoaderRoute: typeof AuthenticatedPaymentsPaymentIdReceiptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/lands/$landId/kml': {
      id: '/api/public/lands/$landId/kml'
      path: '/api/public/lands/$landId/kml'
      fullPath: '/api/public/lands/$landId/kml'
      preLoaderRoute: typeof ApiPublicLandsLandIdKmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFrontdeskRoute: typeof AuthenticatedFrontdeskRoute
  AuthenticatedLand3dRoute: typeof AuthenticatedLand3dRoute
  AuthenticatedLandMappingRoute: typeof AuthenticatedLandMappingRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedLandownersOwnerIdRoute: typeof AuthenticatedLandownersOwnerIdRoute
  AuthenticatedLandsLandIdRoute: typeof AuthenticatedLandsLandIdRoute
  AuthenticatedPayrollComponentsRoute: typeof AuthenticatedPayrollComponentsRoute
  AuthenticatedPayrollStaffRoute: typeof AuthenticatedPayrollStaffRoute
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
  AuthenticatedSettingsLandTypesRoute: typeof AuthenticatedSettingsLandTypesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRentPackagesRoute: typeof AuthenticatedSettingsRentPackagesRoute
  AuthenticatedSettingsSmsRoute: typeof AuthenticatedSettingsSmsRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsZonesRoute: typeof AuthenticatedSettingsZonesRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedLandownersIndexRoute: typeof AuthenticatedLandownersIndexRoute
  AuthenticatedLandsIndexRoute: typeof AuthenticatedLandsIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPayrollIndexRoute: typeof AuthenticatedPayrollIndexRoute
  AuthenticatedPaymentsPaymentIdReceiptRoute: typeof AuthenticatedPaymentsPaymentIdReceiptRoute
  AuthenticatedPayrollPayslipsPayslipIdRoute: typeof AuthenticatedPayrollPayslipsPayslipIdRoute
  AuthenticatedPayrollRunsRunIdRoute: typeof AuthenticatedPayrollRunsRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFrontdeskRoute: AuthenticatedFrontdeskRoute,
  AuthenticatedLand3dRoute: AuthenticatedLand3dRoute,
  AuthenticatedLandMappingRoute: AuthenticatedLandMappingRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedLandownersOwnerIdRoute: AuthenticatedLandownersOwnerIdRoute,
  AuthenticatedLandsLandIdRoute: AuthenticatedLandsLandIdRoute,
  AuthenticatedPayrollComponentsRoute: AuthenticatedPayrollComponentsRoute,
  AuthenticatedPayrollStaffRoute: AuthenticatedPayrollStaffRoute,
  AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
  AuthenticatedSettingsLandTypesRoute: AuthenticatedSettingsLandTypesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsRentPackagesRoute:
    AuthenticatedSettingsRentPackagesRoute,
  AuthenticatedSettingsSmsRoute: AuthenticatedSettingsSmsRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsZonesRoute: AuthenticatedSettingsZonesRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedLandownersIndexRoute: AuthenticatedLandownersIndexRoute,
  AuthenticatedLandsIndexRoute: AuthenticatedLandsIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPayrollIndexRoute: AuthenticatedPayrollIndexRoute,
  AuthenticatedPaymentsPaymentIdReceiptRoute:
    AuthenticatedPaymentsPaymentIdReceiptRoute,
  AuthenticatedPayrollPayslipsPayslipIdRoute:
    AuthenticatedPayrollPayslipsPayslipIdRoute,
  AuthenticatedPayrollRunsRunIdRoute: AuthenticatedPayrollRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicLandsLandIdKmlRoute: ApiPublicLandsLandIdKmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
